name: Team Group-P08-03 CI tasks
on:
  # Execute the workflow when a commit is pushed to the main branch
  push:
    branches:
      - main
  # Execute the workflow when a pull request is opened or updated
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # Build the backend with Maven and run tests
      - name: Build and Test with Maven
        run: ./mvnw --batch-mode --update-snapshots package
        env:
          # H2 Database Configuration
          SPRING_APPLICATION_NAME: webapp
          SPRING_DATASOURCE_URL: jdbc:h2:file:/tmp/VetCare
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
          SPRING_JPA_SHOW_SQL: true
          SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
          SPRING_H2_CONSOLE_ENABLED: true
          SPRING_H2_CONSOLE_PATH: /h2-console
          SPRING_H2_CONSOLE_SETTINGS_TRACE: false
          SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: false
          SPRING_FLYWAY_CLEAN_DISABLED: false
